all:
	g++ -std=c++17 -I../day5.protocol ../day5.protocol/Serialize.cc RpcServer.cc UserService.cc test.cc -o test

debug:
	g++ -g -I../day5.protocol ../day5.protocol/Serialize.cc RpcServer.cc UserService.cc test.cc -o test