all:
	g++ -I../day5.protocal -I../day8.rpc_server -I../day5.protocol test.cc ../day5.protocol/Serialize.cc ../day8.rpc_server/RpcServer.cc ../day8.rpc_server/UserService.cc -o test

debug:
	g++ -g -I../day5.protocal -I../day8.rpc_server -I../day5.protocol test.cc ../day5.protocol/Serialize.cc ../day8.rpc_server/RpcServer.cc ../day8.rpc_server/UserService.cc -o test