name: Release minirpc

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Package
        run: |
          cd build
          cpack -G ZIP -C Release   # 自动生成 ZIP 包

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.repository.releases.latest.upload_url }}
          asset_path: ./build/minirpc-*.zip
          asset_name: minirpc-${{ github.ref_name }}.zip
          asset_content_type: application/zip