name: Release minirpc

on:
  push:
    tags:
      - 'v*' # 仅当推送以 v 开头的标签时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build and Package
        run: |
          cd build
          # 运行 install，将文件复制到临时目录
          cmake --install . --prefix ./install_tmp
          
          # 使用 CPack 打包 install_tmp 目录
          cpack -G ZIP -B ./install_tmp
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.repository.releases.latest.upload_url }}
          asset_path: ./build/install_tmp/minirpc-*.zip
          asset_name: minirpc-${{ github.ref_name }}.zip
          asset_content_type: application/zip